export const GLOSSARY: Record<string, string> = {
  'epic completion': 'The percentage of large planned initiatives that were actually finished. Healthy range: 60\u201380%.',
  'cycle time': 'How long a single piece of work takes from "started" to "done." Lower is better.',
  'bus factor': 'How many people could leave before a project stalls. Higher is safer.',
  'branch protection': 'Automated rules that prevent code from being merged without review. A basic engineering safety net.',
  'priority inflation': 'When most work items are marked "High" priority, making it impossible to distinguish what is actually urgent.',
  'GPV': 'Gross Payment Volume \u2014 the total dollar amount of transactions processed through the payments platform.',
  'take rate': 'The percentage of each transaction the company keeps as revenue.',
  'DORA': 'DevOps Research and Assessment \u2014 the industry standard framework for measuring software delivery performance, developed by Google.',
  'Westrum': 'A model of organizational culture developed by sociologist Ron Westrum. Classifies organizations as pathological, bureaucratic, or generative.',
  'DevEx': 'Developer Experience \u2014 how easy or hard it is for engineers to do their work. Measured across feedback loops, cognitive load, and flow state.',
  'sprint velocity': 'The amount of work a team completes per sprint. Used to forecast future capacity.',
  'story points': 'A relative estimate of effort for a piece of work. Used for planning, not performance measurement.',
  'pipeline success rate': 'The percentage of automated build-and-deploy attempts that succeed. Healthy: >95%.',
  'stale PRs': 'Pull requests (code review submissions) that have been open for weeks or months without being merged or closed.',
  'health check': 'An automated probe that verifies a service is running correctly. Without one, failed services go undetected.',
  'Graviton': 'AWS ARM-based processors that are more cost-efficient and energy-efficient than older x86 instances.',
  'ECS': 'Elastic Container Service \u2014 AWS\u2019s managed service for running containerized applications.',
  'RCA': 'Root Cause Analysis \u2014 a structured investigation into why an incident or outage occurred.',
  'key person risk': 'When critical knowledge or capability is concentrated in one or two individuals. If they leave, the team is blocked.',
  'CI/CD': 'Continuous Integration / Continuous Deployment \u2014 automated systems that build, test, and deploy code changes.',
  'cross-functional': 'Involving multiple departments or teams working together on shared goals.',
  'bridge person': 'Someone who regularly connects two or more departments that otherwise do not interact.',
  'AP': 'Accounts Payable \u2014 money the company owes to vendors and suppliers.',
  'LOC': 'Line of Credit \u2014 a flexible loan arrangement that allows borrowing up to a set limit.',
  'cost of sale': 'The direct cost of delivering a product or service, such as payment processing fees.',
  'churn rate': 'The percentage of customers or merchants who stop using the product over a given period.',
};
