from . import PersonRecord


def _p(name, title, *, manager=None, team=None, division=None, executive=None,
       geography="unknown", status="active", aliases=None):
    return PersonRecord(
        source="org_chart",
        canonical_name=name,
        title=title,
        team=team,
        manager=manager,
        division=division,
        executive=executive,
        geography=geography,
        status=status,
        aliases=aliases or [],
    )


def collect() -> list[PersonRecord]:
    return [
        # ── CEO + Chief of Staff ──
        _p("Don Salama", "Co-CEO",
           manager="Board", division="Executive", executive="Don Salama", geography="US"),
        _p("Ana Chambers", "Chief of Staff Strategic Programs",
           manager="Don Salama", division="Executive", executive="Don Salama", geography="US"),

        # ── Finance (Garcia) ──
        _p("Manuel Garcia", "Interim CFO",
           manager="Don Salama", division="Finance", executive="Manuel Garcia", geography="US"),
        _p("Mark Do", "Assistant Controller",
           manager="Manuel Garcia", team="Finance", division="Finance", executive="Manuel Garcia", geography="US"),
        _p("Zachary Honnold", "RevOps",
           manager="Manuel Garcia", team="Finance", division="Finance", executive="Manuel Garcia", geography="US"),

        # ── Sales & Marketing (Schmitzer) ──
        _p("Greg Schmitzer", "President & Head of Sales & Marketing",
           manager="Don Salama", division="Sales & Marketing", executive="Greg Schmitzer", geography="US"),
        _p("Bobby Jaklitsch", "Field Sales",
           manager="Greg Schmitzer", team="Sales", division="Sales & Marketing", executive="Greg Schmitzer", geography="US"),
        _p("Peter Vu", "Inbound Sales",
           manager="Greg Schmitzer", team="Sales", division="Sales & Marketing", executive="Greg Schmitzer", geography="US"),
        _p("Karen Licker", "Marketing",
           manager="Greg Schmitzer", team="Marketing", division="Sales & Marketing", executive="Greg Schmitzer", geography="US"),

        # ── Operations (Strainick) ──
        _p("David Strainick", "COO",
           manager="Don Salama", division="Operations", executive="David Strainick", geography="US"),
        _p("Das DeSilva", "Onboarding",
           manager="David Strainick", team="Onboarding", division="Operations", executive="David Strainick", geography="US"),
        _p("Rosen Georgiev", "IT Ops",
           manager="David Strainick", team="IT Ops", division="Operations", executive="David Strainick", geography="US"),
        _p("Chip O'Connell", "Onboarding Delivery",
           manager="David Strainick", team="Onboarding", division="Operations", executive="David Strainick", geography="US"),

        # ── CDO ──
        _p("Chathura Ratnayake", "CDO",
           manager="Don Salama", division="CDO", executive="Chathura Ratnayake", geography="US"),

        # ── Product & GTM (Dulanjan) ──
        _p("Dulanjan Wengappuliarachchi", "VP Product & GTM",
           manager="Chathura Ratnayake", team="Product", division="CDO / Product & GTM",
           executive="Chathura Ratnayake", geography="SL", aliases=["Dulanjan W."]),
        _p("Miru Somasunthara Iyer", "Senior Product Manager",
           manager="Dulanjan Wengappuliarachchi", team="Product Restaurant",
           division="CDO / Product & GTM", executive="Chathura Ratnayake",
           aliases=["Miru S.", "Mirunaaliny Somasunthara Iyer"]),
        _p("Jake L.", "Product Manager",
           manager="Dulanjan Wengappuliarachchi", team="Product Restaurant",
           division="CDO / Product & GTM", executive="Chathura Ratnayake"),
        _p("Shavin Pieris", "Senior Product Manager",
           manager="Dulanjan Wengappuliarachchi", team="Product Payments",
           division="CDO / Product & GTM", executive="Chathura Ratnayake", aliases=["Shavin P."]),
        _p("Richard Farber", "Product Manager",
           manager="Dulanjan Wengappuliarachchi", team="Product",
           division="CDO / Product & GTM", executive="Chathura Ratnayake", aliases=["Richard F."]),
        _p("Thaddeus Fox", "Product Manager",
           manager="Dulanjan Wengappuliarachchi", team="Product",
           division="CDO / Product & GTM", executive="Chathura Ratnayake", aliases=["Thaddeus F."]),
        _p("Chris Gomersall", "Director Product Design",
           manager="Dulanjan Wengappuliarachchi", team="Product Design",
           division="CDO / Product & GTM", executive="Chathura Ratnayake", geography="US"),
        _p("Adriana Zuniga", "Technical Training Specialist",
           manager="Dulanjan Wengappuliarachchi", team="L&D",
           division="CDO / Product & GTM", executive="Chathura Ratnayake", aliases=["Adriana Z."]),
        _p("Ayodele Lawal", "Technical Training Specialist",
           manager="Dulanjan Wengappuliarachchi", team="L&D",
           division="CDO / Product & GTM", executive="Chathura Ratnayake", aliases=["Ayodele L."]),

        # ── Restaurant Technology (Randy Brown) ──
        _p("Randy Brown", "VP Engineering Restaurant Technology",
           manager="Chathura Ratnayake", team="Restaurant",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake", geography="US"),
        _p("Alexander Baine", "Manager Software Engineering",
           manager="Randy Brown", team="Restaurant Frontend",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake", geography="US"),
        _p("Cory Renard", "Staff Software Engineer",
           manager="Alexander Baine", team="Restaurant Frontend",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake"),
        _p("Rob Quin", "Software Engineer",
           manager="Alexander Baine", team="Restaurant Frontend",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake"),
        _p("Kyle Budd", "Manager Software Engineering",
           manager="Randy Brown", team="Restaurant Backend",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake"),
        _p("Beau Bruderer", "Senior Software Engineer",
           manager="Kyle Budd", team="Restaurant Backend",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake"),
        _p("Holly Bobal", "Senior Software Engineer",
           manager="Kyle Budd", team="Restaurant Backend",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake"),
        _p("Siva Ganesh", "Software Engineer",
           manager="Kyle Budd", team="Restaurant Backend",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake"),
        _p("Harrison Minchew", "Lead Software Engineer",
           manager="Kyle Budd", team="Restaurant Backend",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake"),
        _p("Anderson Lavor", "Lead Software Engineer",
           manager="Kyle Budd", team="Restaurant Backend",
           division="CDO / Restaurant Technology", executive="Chathura Ratnayake"),

        # ── Enterprise Solutions (Zubair) ──
        _p("Zubair Syed", "VP Engineering Enterprise Solutions",
           manager="Chathura Ratnayake", team="Enterprise",
           division="CDO / Enterprise Solutions", executive="Chathura Ratnayake"),

        # ── Payments & Financial Services (Akshay) ──
        _p("Akshay Bhasin", "VP Payments Engineering",
           manager="Chathura Ratnayake", team="Payments",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake", geography="US"),
        _p("Kevin Reyes", "Director Software Engineering",
           manager="Akshay Bhasin", team="Payments R&D",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake", geography="US"),
        _p("Trenton Kress", "Staff Software Engineer",
           manager="Kevin Reyes", team="Payments R&D",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Pratikchha Kahdka", "Software Engineer",
           manager="Kevin Reyes", team="Payments R&D",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Peter Wu", "Staff Software Engineer",
           manager="Kevin Reyes", team="Payments R&D",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           aliases=["Wing Hung Peter Wu"]),
        _p("Paul Robert", "Senior Software Engineer",
           manager="Kevin Reyes", team="Payments R&D",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           aliases=["paul.roberts"]),
        _p("Richard Meitzler", "Staff Software Engineer",
           manager="Kevin Reyes", team="Payments R&D",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Gayan Karunarathna", "Staff Software Engineer",
           manager="Kevin Reyes", team="Payments R&D",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           geography="SL", aliases=["Gayan K"]),
        _p("Susampath Madarasinghe", "Senior Software Engineer",
           manager="Kevin Reyes", team="Payments R&D",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           geography="SL", aliases=["Susampath M"]),
        _p("Matthew Griffin", "Senior Cloud Engineer",
           manager="Kevin Reyes", team="Payments R&D",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake", geography="US"),
        _p("Sowjanya Akula", "Senior Quality Engineer",
           manager="Akshay Bhasin", team="Restaurant QE",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Danika M", "Senior Quality Engineer",
           manager="Akshay Bhasin", team="Restaurant QE",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           geography="SL", aliases=["Danika M (SL)"]),
        _p("Darren Blackwell", "Quality Automation Engineer",
           manager="Akshay Bhasin", team="Restaurant QE",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Rekha Mohanan", "Senior Quality Engineer",
           manager="Akshay Bhasin", team="Restaurant QE",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Bill Fenley", "Senior Software Engineer Quality",
           manager="Akshay Bhasin", team="Restaurant QE",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Kaelon Lucas", "Quality Automation Engineer",
           manager="Akshay Bhasin", team="Restaurant QE",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Patrycja Stevenson", "Senior Software Engineer Quality",
           manager="Akshay Bhasin", team="Restaurant QE",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Andy Honnold", "Sr Director Payments Strategy",
           manager="Akshay Bhasin", team="Payments Biz Ops",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake", geography="US"),
        _p("Altaaf A", "Payment Operations Manager",
           manager="Andy Honnold", team="Payments Biz Ops",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           geography="SL", aliases=["Altaaf A (SL)"]),
        _p("Kanchana A", "Senior Payments Operations Analyst",
           team="Payments Biz Ops",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           geography="SL", aliases=["Kanchana A (SL)"]),
        _p("Angie Mroczka", "Payment Risk Fraud Analyst",
           manager="Andy Honnold", team="Payments Biz Ops",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Mark Freid", "Senior Security Engineer",
           manager="Akshay Bhasin", team="PCI Compliance",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Debbie Keye", "PMO",
           manager="Akshay Bhasin", team="PCI Compliance",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           aliases=["Debbie K."]),
        _p("Jorge Maltes", "Dir Information Technology",
           manager="Akshay Bhasin", team="PCI Compliance",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake"),
        _p("Matias Lopez Riglos", "Solution Operations",
           manager="Akshay Bhasin", team="PCI Compliance",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           aliases=["Matias Riglos"]),
        _p("Vanessa Sotomayor", "Program Manager",
           manager="Akshay Bhasin", team="Payments PMO",
           division="CDO / Payments & Financial Services", executive="Chathura Ratnayake",
           aliases=["Vanessa S."]),

        # ── PMO (Guilarte) ──
        _p("Mark Guilarte", "VP Program Management",
           manager="Chathura Ratnayake", team="PMO",
           division="CDO / PMO", executive="Chathura Ratnayake"),
        _p("Qaiser Pannu", "Senior Program Manager",
           manager="Mark Guilarte", team="PMO Restaurant",
           division="CDO / PMO", executive="Chathura Ratnayake", aliases=["Qaiser P."]),
        _p("Ian B.", "Project Lead",
           manager="Mark Guilarte", team="PMO AI",
           division="CDO / PMO", executive="Chathura Ratnayake"),

        # ── CTO (Kennedy) ──
        _p("Jack Kennedy", "CTO",
           manager="Don Salama", division="CTO", executive="Jack Kennedy", geography="US"),
        _p("Jeremy Diggins", "Director Enterprise Technology",
           manager="Jack Kennedy", team="Enterprise Technology",
           division="CTO", executive="Jack Kennedy", geography="US"),

        # ── HR (Shatney) ──
        _p("Bailey Shatney", "VP Human Resources",
           manager="Don Salama", division="HR", executive="Bailey Shatney", geography="US"),
        _p("Renee Pauley", "Recruiting",
           manager="Bailey Shatney", team="Recruiting",
           division="HR", executive="Bailey Shatney"),

        # ── Sri Lanka ──
        _p("Rajik Gunatilaka", "VP & LK Country Head",
           manager="David Strainick", division="Operations / Sri Lanka",
           executive="David Strainick", geography="SL"),

        # ── Departed / Consulting ──
        _p("Steven Siegel", "Former COO",
           division="Executive", status="departed"),
        _p("Bill Lodes", "Former CRO",
           division="Sales & Marketing", status="consulting"),
    ]


_JIRA_PROJECT_TEAM_MAP = {
    "REST": "Restaurant",
    "POS": "Restaurant",
    "DR": "Restaurant",
    "KDS": "Restaurant",
    "TESTREST": "Restaurant",
    "DSO": "Enterprise",
    "CE": "Enterprise",
    "CLOUD": "Enterprise",
    "PAY": "Payments",
    "MP": "Payments",
    "NEO": "AI/Innovation",
    "AI": "AI/Innovation",
    "AAK": "AI/Innovation",
    "LAA": "AI/Innovation",
    "OS": "Platform",
    "PLTFRM": "Platform",
    "PLAT": "Platform",
}

_WORKSPACE_DIVISION_MAP = {
    "syscolabs": "CAKE / Restaurant",
    "madpayments": "Payments",
    "madmobile": "Concierge / Retail / Platform",
    "syscolabsconf": "CAKE Legacy",
}


def get_team_for_project(project_key: str) -> str:
    return _JIRA_PROJECT_TEAM_MAP.get(project_key.upper(), "Unknown")


def get_division_for_workspace(workspace: str) -> str:
    return _WORKSPACE_DIVISION_MAP.get(workspace.lower(), "Unknown")
